#ifndef FILECUTTERLIB_GLOBAL_H
#define FILECUTTERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILECUTTERLIB_LIBRARY)
#  define FILECUTTERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILECUTTERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILECUTTERLIB_GLOBAL_H
